### PR TITLE
Broken demo URL in readme

### PR DESCRIPTION
**Pull request by bpod**
- fixes broken URL in README

### CODE REVIEW

**Comment by bpod** [comment]
grrrr... looking into why this is breaking

**Comment by joshghent** [comment]
@bpod Looks like this is the issue with Rollbar stuff in #23 - don't worry about it. We can fix it there, and with the react rewrite you are working on, all this will be in the past.

**Comment by bpod** [comment]
Yea.. makes sense. I have some other questions but I'll follow up in #21.

**Comment by joshghent** [comment]
@bpod Ok after looking into it, looks like supertest is not exiting correctly.

**Comment by bpod** [comment]
I'm going to close this PR and address any other concerns in my React Branch. 👍

**Pull request closed without merging**
